# .github/workflows/dbt-ci.yml
name: CI

on:
  push:
    branches:
      - main

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Install dbt
        run: pip install dbt-core==1.9.4 dbt-postgres==1.9.4

      - name: Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          first_dw:
            target: prod
            outputs:
              prod:
                type: postgres
                threads: 4
                host: ${{ secrets.RENDER_DB_HOST }}
                user: ${{ secrets.RENDER_DB_USER }}
                pass: ${{ secrets.RENDER_DB_PASS }}
                port: ${{ secrets.RENDER_DB_PORT }}
                dbname: ${{ secrets.RENDER_DB_NAME }}
                schema: public
          EOF
      
      - name: Debug environment
        working-directory: first_dw
        run: |
          ls -la
          cat packages.yml
          cat dbt_project.yml
           
      - name: dbt deps
        working-directory: first_dw
        run: dbt deps --profiles-dir ~/.dbt --debug


      - name: dbt build
        working-directory: first_dw
        run: dbt build --profiles-dir ~/.dbt